import type { Metadata } from "next";
import { DM_Sans, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/common/header";
import Sidebar from "@/components/common/sidebar";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const dm_sans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "PIBEC - Web App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

      <html
        lang="en"
        className={cn("h-full", "antialiased", dm_sans.className, "font-sans", inter.variable)}
      >
        <body className="min-h-screen flex flex-col bg-background">
          <Header />

          {/* Mudamos para flex-col no mobile e flex-row (lado a lado) no desktop (sm) */}
          <div className="flex flex-col sm:flex-row flex-1">
            <Sidebar /> 

            <main className="flex-1 p-4 sm:p-6">
              {children}
            </main>
          </div>
        </body>
      
      </html>
    </ClerkProvider>
    
  );
}